# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-30 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='distance_archievement_date',
            new_name='distance_achievement_date',
        ),
    ]
